gpu_num: 4

gspe:
  T: 0.1
  type: Chamfer

pretrain:
  is_resume: False
  ckpt_path:
  ckpt_epoch: 1
  max_checkpoints: 2
  epochs: 10
  lr: 0.005
  weight_decay: 0.001
  step_size: 5
  gamma: 0.1

finetune:
  freeze_models:
    - 
  is_lora: True
  is_resume: False
  ckpt_path:
  ckpt_epoch: 2
  max_checkpoints: 2
  epochs: 70
  lr: 0.0001
  weight_decay: 0.001
  step_size: 15
  gamma: 0.5

inference:
  ckpt_path:

lora:
  rank: 8
  alpha: 32
  dropout: 0.1
  bias: none
  target_modules:
    - q_proj
    - v_proj
    - decoder
  task_type: CAUSAL_LM


